import type {
  HomepageCalendarItem,
  HomepageCategoryPill,
  HomepageImageRailItem,
  HomepageLowerModule,
  HomepageNavItem,
  HomepageSignalItem,
  HomepageVenueCard,
} from './homepage-types';

export const HOMEPAGE_NAV_ITEMS: HomepageNavItem[] = [
  { label: 'Tonight', href: '/tonight' },
  { label: 'Venues', href: '/venues' },
  { label: 'Guides', href: '/guides' },
  { label: 'Events', href: '/events' },
  { label: 'Membership', href: '/membership' },
];

export const HOMEPAGE_CATEGORY_PILLS: HomepageCategoryPill[] = [
  { label: 'Live Now', icon: '●', active: true },
  { label: 'Live Music', icon: '🎸' },
  { label: 'Rooftops', icon: '🌆' },
  { label: 'Late Eats', icon: '🌮' },
  { label: 'Good Eats', icon: '🍽' },
  { label: 'Cocktails', icon: '🍸' },
  { label: 'Dancing', icon: '✨' },
  { label: 'Comedy', icon: '🎤' },
  { label: 'Shopping', icon: '🛍' },
  { label: 'Sales', icon: '🏷' },
  { label: 'Brunch', icon: '🥂' },
  { label: 'Pet Sitting', icon: '🐾' },
  { label: 'Pet Friendly', icon: '🐶' },
  { label: 'Deals', icon: '💸' },
];

export const HOMEPAGE_VENUE_CARDS: HomepageVenueCard[] = [
  {
    id: 'venue-1',
    slug: 'mohawk-atx-wild-child',
    title: 'Mohawk ATX',
    venueName: 'Mohawk ATX',
    neighborhood: 'Red River',
    category: 'Live Music',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80',
    statusBadge: 'Live Now',
    timeLabel: '8:30 PM',
    ratingLabel: '4.8',
    availabilityLabel: 'Filling Fast',
    availabilityTone: 'hot',
    tags: ['Outdoor Stage', 'Editorial Pick'],
    ctaLabel: 'Explore',
    href: '/venues#mohawk-atx-wild-child',
  },
  {
    id: 'venue-2',
    slug: 'craft-pride-rainey',
    title: 'Craft Pride',
    venueName: 'Craft Pride',
    neighborhood: 'Rainey Street',
    category: 'Cocktails',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1200&q=80',
    statusBadge: 'Open Late',
    timeLabel: '9:00 PM',
    ratingLabel: '4.7',
    availabilityLabel: 'Open Late',
    availabilityTone: 'warm',
    tags: ['Craft Cocktails', 'Neighborhood Heat'],
    ctaLabel: 'Explore',
    href: '/venues#craft-pride-rainey',
  },
  {
    id: 'venue-3',
    slug: 'cap-city-comedy-late-show',
    title: 'Cap City Comedy',
    venueName: 'Cap City Comedy',
    neighborhood: 'North Lamar',
    category: 'Comedy',
    image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=1200&q=80',
    statusBadge: 'Good Seats',
    timeLabel: '10:00 PM',
    ratingLabel: '4.6',
    availabilityLabel: 'Good Seats Left',
    availabilityTone: 'steady',
    tags: ['Comedy', 'Date Night'],
    ctaLabel: 'Explore',
    href: '/venues#cap-city-comedy-late-show',
  },
  {
    id: 'venue-4',
    slug: 'rooftop-east-austin',
    title: 'Higher Ground',
    venueName: 'Higher Ground',
    neighborhood: 'East Austin',
    category: 'Rooftops',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&q=80',
    statusBadge: 'High Energy',
    timeLabel: '10:30 PM',
    ratingLabel: '4.9',
    availabilityLabel: 'Almost Gone',
    availabilityTone: 'hot',
    tags: ['Rooftop', 'Night Views'],
    ctaLabel: 'Explore',
    href: '/venues#rooftop-east-austin',
  },
];

export const HOMEPAGE_SIGNAL_ITEMS: HomepageSignalItem[] = [
  {
    id: 'signal-1',
    district: 'East 6th St',
    heatLabel: 'Hot',
    trendLabel: 'Very High Energy',
    categoryHint: 'Tonight Peak',
    href: '/tonight?district=east-6th-st',
    rank: 1,
    mapX: '52%',
    mapY: '32%',
  },
  {
    id: 'signal-2',
    district: 'Rainey St',
    heatLabel: 'Warm',
    trendLabel: 'High Energy',
    categoryHint: 'Open Late',
    href: '/tonight?district=rainey-st',
    rank: 2,
    mapX: '48%',
    mapY: '82%',
  },
  {
    id: 'signal-3',
    district: 'South Congress',
    heatLabel: 'Steady',
    trendLabel: 'Steady',
    categoryHint: 'Locals Night',
    href: '/tonight?district=south-congress',
    rank: 3,
    mapX: '22%',
    mapY: '22%',
  },
  {
    id: 'signal-4',
    district: 'Downtown',
    heatLabel: 'Warm',
    trendLabel: 'Steady Flow',
    categoryHint: 'Skyline',
    href: '/tonight?district=downtown',
    rank: 4,
    mapX: '36%',
    mapY: '56%',
  },
  {
    id: 'signal-5',
    district: 'East Austin',
    heatLabel: 'Hot',
    trendLabel: 'Rising',
    categoryHint: 'Late Bars',
    href: '/tonight?district=east-austin',
    rank: 5,
    mapX: '68%',
    mapY: '56%',
  },
];

export const HOMEPAGE_CALENDAR_ITEMS: HomepageCalendarItem[] = [
  {
    id: 'calendar-1',
    dayLabel: 'Tonight',
    dateLabel: 'Fri · May 15',
    timeLabel: '8:30 PM',
    title: 'The Format + Night Moves',
    venue: 'Mohawk Austin',
    neighborhood: 'Red River',
    category: 'Live Music',
    status: 'Selling fast',
    href: '/events',
  },
  {
    id: 'calendar-2',
    dayLabel: 'Tonight',
    dateLabel: 'Fri · May 15',
    timeLabel: '10:00 PM',
    title: 'Late Show Stand-Up',
    venue: 'Cap City Comedy',
    neighborhood: 'North Lamar',
    category: 'Comedy',
    status: 'Good seats',
    href: '/events',
  },
  {
    id: 'calendar-3',
    dayLabel: 'Tomorrow',
    dateLabel: 'Sat · May 16',
    timeLabel: '11:00 AM',
    title: 'Rooftop Brunch Session',
    venue: 'Higher Ground',
    neighborhood: 'East Austin',
    category: 'Brunch',
    status: 'Reservations open',
    href: '/events',
  },
  {
    id: 'calendar-4',
    dayLabel: 'Tomorrow',
    dateLabel: 'Sat · May 16',
    timeLabel: '8:00 PM',
    title: 'ACL Live Weekend Spotlight',
    venue: 'ACL Live',
    neighborhood: 'Downtown',
    category: 'Live Music',
    status: 'Featured',
    href: '/events',
  },
  {
    id: 'calendar-5',
    dayLabel: 'Sunday',
    dateLabel: 'Sun · May 17',
    timeLabel: '1:00 PM',
    title: 'South Congress Patio Crawl',
    venue: 'South Congress Strip',
    neighborhood: 'South Congress',
    category: 'Cocktails',
    status: 'Walk-up friendly',
    href: '/events',
  },
  {
    id: 'calendar-6',
    dayLabel: 'Sunday',
    dateLabel: 'Sun · May 17',
    timeLabel: '6:30 PM',
    title: 'Sunset Comedy + Cocktails',
    venue: 'East Austin Social',
    neighborhood: 'East Austin',
    category: 'Comedy',
    status: 'Locals pick',
    href: '/events',
  },
  {
    id: 'calendar-7',
    dayLabel: 'Next Week',
    dateLabel: 'Thu · May 21',
    timeLabel: '7:30 PM',
    title: 'Antone\'s Blues Night',
    venue: 'Antone\'s',
    neighborhood: 'Downtown',
    category: 'Live Music',
    status: 'On sale',
    href: '/events',
  },
  {
    id: 'calendar-8',
    dayLabel: 'Next Week',
    dateLabel: 'Sat · May 23',
    timeLabel: '9:00 PM',
    title: 'Rainey Late-Night Roundup',
    venue: 'Rainey Street District',
    neighborhood: 'Rainey Street',
    category: 'Dancing',
    status: 'Open late',
    href: '/events',
  },
];

export const HOMEPAGE_LOWER_MODULES: HomepageLowerModule[] = [
  {
    id: 'que-pasa',
    title: 'Que Pasa',
    caption: 'What\u2019s happening across Austin tonight.',
    icon: '\u2728',
    accent: 'pink',
    href: '/tonight',
  },
  {
    id: 'community',
    title: 'Community',
    caption: 'Real locals, real picks, real reviews.',
    icon: '\u25c6',
    accent: 'violet',
    href: '/community-guidelines',
  },
  {
    id: 'pupper-weekly',
    title: 'Pupper Weekly',
    caption: 'Pet-friendly patios, sits, and dog events.',
    icon: '\ud83d\udc3e',
    accent: 'amber',
    href: '/guides',
  },
  {
    id: 'the-weather',
    title: 'The Weather',
    caption: 'Tonight\u2019s sky, heat, and rain calls.',
    icon: '\u2604',
    accent: 'cyan',
    href: '/guides',
  },
  {
    id: 'calendar',
    title: 'Calendar',
    caption: 'Plan ahead \u2014 weekend through next month.',
    icon: '\u2756',
    accent: 'lime',
    href: '/events',
  },
];

export const HOMEPAGE_IMAGE_RAIL: HomepageImageRailItem[] = [
  {
    id: 'rail-1',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&q=80',
    caption: 'Crowd energy that feels like Austin, not a generic nightlife app.',
    neighborhood: 'Red River',
    category: 'Live Music',
    href: '/venues#mohawk-atx-wild-child',
    rightsStatus: 'curated',
    attribution: 'Curated reference image',
  },
  {
    id: 'rail-2',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200&q=80',
    caption: 'Food, drinks, and people/place texture belong in the frame.',
    neighborhood: 'East Austin',
    category: 'Late Eats',
    href: '/events',
    rightsStatus: 'approved',
    attribution: 'Approved reference image',
  },
  {
    id: 'rail-3',
    image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?w=1200&q=80',
    caption: 'Editorial nightlife mood beats a sterile event grid every time.',
    neighborhood: 'Rainey Street',
    category: 'Cocktails',
    href: '/venues#craft-pride-rainey',
    rightsStatus: 'permissioned',
    attribution: 'Permissioned reference image',
  },
];
