import type {
  HomepageCalendarItem,
  HomepageCategoryPill,
  HomepageImageRailItem,
  HomepageLowerModule,
  HomepageNavItem,
  HomepageSignalItem,
  HomepageVenueCard,
} from './homepage-types';

export const HOMEPAGE_NAV_ITEMS: HomepageNavItem[] = [
  { label: 'Tonight', href: '/tonight' },
  { label: 'Venues', href: '/venues' },
  { label: 'Guides', href: '/guides' },
  { label: 'Events', href: '/events' },
  { label: 'Preview List', href: '/membership' },
];

export const HOMEPAGE_CATEGORY_PILLS: HomepageCategoryPill[] = [
  { label: 'Live Music', icon: '🎸' },
  { label: 'Rooftops', icon: '🌆' },
  { label: 'Late Eats', icon: '🌮' },
  { label: 'Good Eats', icon: '🍽' },
  { label: 'Cocktails', icon: '🍸' },
  { label: 'Dancing', icon: '✨' },
  { label: 'Comedy', icon: '🎤' },
];

// Sourced from Leonardo's verified venue files (workspace-leonardo/memory/venues-*.md),
// Galileo QA PASS 2026-06-12 + 2026-06-13. Real Austin venues only — no fabricated
// ratings/times/photos; unresolvable fields left empty per QA. Closed (Barracuda) and
// quarantined-junk rows excluded. Discovery click (href) -> /tonight filter SET;
// websiteUrl -> the venue's real, verified site (rendered as a secondary "Visit site" link).
export const HOMEPAGE_VENUE_CARDS: HomepageVenueCard[] = [
  // --- LIVE MUSIC ---
  {
    id: 'venue-1',
    slug: 'mohawk-atx',
    cardArtUrl: '/assets/venue-art/livemusic-v5neon.png',
    title: 'Mohawk ATX',
    venueName: 'Mohawk',
    neighborhood: 'Red River',
    category: 'Live Music',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'hot',
    tags: ['Live Music', 'Indie Club'],
    ctaLabel: 'See Live Music picks',
    href: '/tonight?category=live-music',
    websiteUrl: 'https://mohawkaustin.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-2',
    slug: 'stubbs-bar-b-q',
    cardArtUrl: '/assets/venue-art/livemusic-v3austin.png',
    title: "Stubb's Bar-B-Q",
    venueName: "Stubb's Bar-B-Q",
    neighborhood: 'Red River',
    category: 'Live Music',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'hot',
    tags: ['Live Music', 'BBQ'],
    ctaLabel: 'See Live Music picks',
    href: '/tonight?category=live-music',
    websiteUrl: 'https://stubbsaustin.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-3',
    slug: 'continental-club',
    cardArtUrl: '/assets/venue-art/livemusic-v1warm.png',
    title: 'The Continental Club',
    venueName: 'The Continental Club',
    neighborhood: 'South Congress',
    category: 'Live Music',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Live Music', 'Historic'],
    ctaLabel: 'See Live Music picks',
    href: '/tonight?category=live-music',
    websiteUrl: 'https://continentalclub.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-4',
    slug: 'antones-nightclub',
    cardArtUrl: '/assets/venue-art/livemusic-v2sharp.png',
    title: "Antone's Nightclub",
    venueName: "Antone's Nightclub",
    neighborhood: 'Downtown',
    category: 'Live Music',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Live Music', 'Blues'],
    ctaLabel: 'See Live Music picks',
    href: '/tonight?category=live-music',
    websiteUrl: 'https://antonesnightclub.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-5',
    slug: 'c-boys-heart-soul',
    cardArtUrl: '/assets/venue-art/livemusic-v4austin.png',
    title: 'C-Boys Heart & Soul',
    venueName: 'C-Boys Heart & Soul',
    neighborhood: 'South Congress',
    category: 'Live Music',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Live Music', 'Soul Food'],
    ctaLabel: 'See Live Music picks',
    href: '/tonight?category=live-music',
    websiteUrl: undefined, // dead link removed 2026-06-18 audit — NXDOMAIN (does not resolve)
    hasDetailPage: false,
  },
  // --- ROOFTOPS ---
  {
    id: 'venue-6',
    slug: 'azul-rooftop',
    cardArtUrl: '/assets/venue-art/rooftop-v3austin.png',
    title: 'Azul Rooftop Bar + Lounge',
    venueName: 'Azul Rooftop Bar + Lounge',
    neighborhood: 'Downtown',
    category: 'Rooftops',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'hot',
    tags: ['Rooftop', 'Skyline Views'],
    ctaLabel: 'See Rooftops picks',
    href: '/tonight?category=rooftops',
    websiteUrl: 'https://azulrooftopatx.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-7',
    slug: 'rooftop-on-6th',
    cardArtUrl: '/assets/venue-art/rooftop-v5neon.png',
    title: 'The Rooftop on 6th',
    venueName: 'The Rooftop on 6th',
    neighborhood: 'Downtown',
    category: 'Rooftops',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'hot',
    tags: ['Rooftop', 'Nightclub'],
    ctaLabel: 'See Rooftops picks',
    href: '/tonight?category=rooftops',
    websiteUrl: undefined, // dead link removed 2026-06-18 audit — NXDOMAIN (does not resolve)
    hasDetailPage: false,
  },
  {
    id: 'venue-8',
    slug: 'luna-rooftop',
    cardArtUrl: '/assets/venue-art/rooftop-v4austin.png',
    title: 'Luna Rooftop',
    venueName: 'Luna Rooftop',
    neighborhood: 'Downtown',
    category: 'Rooftops',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'warm',
    tags: ['Rooftop', 'DJ Nights'],
    ctaLabel: 'See Rooftops picks',
    href: '/tonight?category=rooftops',
    websiteUrl: 'https://lunarooftopatx.com',
    hasDetailPage: false,
  },
  // --- LATE EATS ---
  {
    id: 'venue-9',
    slug: 'dittydog',
    cardArtUrl: '/assets/venue-art/foodtruck-park-v6.png',
    title: 'DittyDog',
    venueName: 'DittyDog',
    neighborhood: 'Downtown',
    category: 'Late Eats',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'warm',
    tags: ['Late Night', 'Hot Dogs'],
    ctaLabel: 'See Late Eats picks',
    href: '/tonight?category=late-eats',
    websiteUrl: 'https://dittydog.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-10',
    slug: 'always-something',
    cardArtUrl: '/assets/venue-art/foodtruck-park-v6.png',
    title: 'Always Something',
    venueName: 'Always Something',
    neighborhood: 'Rainey Street',
    category: 'Late Eats',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'warm',
    tags: ['Food Trucks', 'Late Night'],
    ctaLabel: 'See Late Eats picks',
    href: '/tonight?category=late-eats',
    websiteUrl: 'https://alwayssomethingatx.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-11',
    slug: 'veracruz-all-natural',
    cardArtUrl: '/assets/venue-art/lively-eatery-v7.png',
    title: 'Veracruz All Natural',
    venueName: 'Veracruz All Natural',
    neighborhood: 'South Congress',
    category: 'Late Eats',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Tacos', 'Local Favorite'],
    ctaLabel: 'See Late Eats picks',
    href: '/tonight?category=late-eats',
    websiteUrl: 'https://veracruzallnatural.com',
    hasDetailPage: false,
  },
  // --- GOOD EATS ---
  {
    id: 'venue-12',
    slug: 'franklin-barbecue',
    cardArtUrl: '/assets/venue-art/bbq-smokehouse-v4austin.png',
    title: 'Franklin Barbecue',
    venueName: 'Franklin Barbecue',
    neighborhood: 'East Austin',
    category: 'Good Eats',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'hot',
    tags: ['BBQ', 'Austin Icon'],
    ctaLabel: 'See Good Eats picks',
    href: '/tonight?category=good-eats',
    websiteUrl: 'https://franklinbbq.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-13',
    slug: 'bangers-beer-garden',
    cardArtUrl: '/assets/venue-art/beer-garden-v6.png',
    title: "Banger's Sausage House & Beer Garden",
    venueName: "Banger's Sausage House & Beer Garden",
    neighborhood: 'Rainey Street',
    category: 'Good Eats',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'warm',
    tags: ['Beer Garden', 'Sausages'],
    ctaLabel: 'See Good Eats picks',
    href: '/tonight?category=good-eats',
    websiteUrl: 'https://bangersaustin.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-14',
    slug: 'loro-south-lamar',
    cardArtUrl: '/assets/venue-art/smokehouse-v5neon.png',
    title: 'Loro',
    venueName: 'Loro (South Lamar)',
    neighborhood: 'South Lamar',
    category: 'Good Eats',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Asian Smokehouse', 'Patio'],
    ctaLabel: 'See Good Eats picks',
    href: '/tonight?category=good-eats',
    websiteUrl: 'https://loroeats.com',
    hasDetailPage: false,
  },
  // --- COCKTAILS ---
  {
    id: 'venue-15',
    slug: 'here-nor-there',
    cardArtUrl: '/assets/venue-art/cozy-indoor-bar-v6.png',
    title: 'Here Nor There',
    venueName: 'Here Nor There',
    neighborhood: 'Downtown',
    category: 'Cocktails',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Speakeasy', 'Cocktails'],
    ctaLabel: 'See Cocktails picks',
    href: '/tonight?category=cocktails',
    websiteUrl: 'https://hntaustin.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-16',
    slug: 'garage-atx',
    cardArtUrl: '/assets/venue-art/cocktails-v5neon.png',
    title: 'Garage',
    venueName: 'Garage',
    neighborhood: 'Downtown',
    category: 'Cocktails',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Speakeasy', 'Cocktails'],
    ctaLabel: 'See Cocktails picks',
    href: '/tonight?category=cocktails',
    websiteUrl: 'https://garagetx.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-17',
    slug: 'kinfolk-lounge',
    cardArtUrl: '/assets/venue-art/cocktails-v1warm.png',
    title: 'Kinfolk Lounge & Library',
    venueName: 'Kinfolk Lounge & Library',
    neighborhood: 'Red River',
    category: 'Cocktails',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Cocktail Lounge', 'Spirits Library'],
    ctaLabel: 'See Cocktails picks',
    href: '/tonight?category=cocktails',
    websiteUrl: 'https://kinfolkaustin.com',
    hasDetailPage: false,
  },
  // --- DANCING ---
  {
    id: 'venue-18',
    slug: 'white-horse',
    cardArtUrl: '/assets/venue-art/honkytonk-band-v6.png',
    title: 'The White Horse',
    venueName: 'The White Horse',
    neighborhood: 'East Austin',
    category: 'Dancing',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'hot',
    tags: ['Honky-Tonk', 'Two-Step'],
    ctaLabel: 'See Dancing picks',
    href: '/tonight?category=dancing',
    websiteUrl: undefined, // dead link removed 2026-06-18 audit — domain-parking lander (/lander redirect)
    hasDetailPage: false,
  },
  {
    id: 'venue-19',
    slug: 'barbarella',
    cardArtUrl: '/assets/venue-art/dance-club-v5neon.png',
    title: 'Barbarella',
    venueName: 'Barbarella',
    neighborhood: 'Red River',
    category: 'Dancing',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'warm',
    tags: ['Dance Club', 'Theme Nights'],
    ctaLabel: 'See Dancing picks',
    href: '/tonight?category=dancing',
    websiteUrl: undefined, // dead link removed 2026-06-18 audit — HTTPS/TLS handshake fails (won't load)
    hasDetailPage: false,
  },
  {
    id: 'venue-20',
    slug: 'broken-spoke',
    cardArtUrl: '/assets/venue-art/two-step-v6.png',
    title: 'Broken Spoke',
    venueName: 'Broken Spoke',
    neighborhood: 'South Lamar',
    category: 'Dancing',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Honky-Tonk', 'Dance Hall'],
    ctaLabel: 'See Dancing picks',
    href: '/tonight?category=dancing',
    websiteUrl: 'https://brokenspokeaustintx.net',
    hasDetailPage: false,
  },
  // --- COMEDY ---
  {
    id: 'venue-21',
    slug: 'comedy-mothership',
    cardArtUrl: '/assets/venue-art/comedy-v5neon.png',
    title: 'The Comedy Mothership',
    venueName: 'The Comedy Mothership',
    neighborhood: 'Downtown',
    category: 'Comedy',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'hot',
    tags: ['Stand-Up', 'Headliners'],
    ctaLabel: 'See Comedy picks',
    href: '/tonight?category=comedy',
    websiteUrl: undefined, // dead link removed 2026-06-18 audit — NXDOMAIN (does not resolve)
    hasDetailPage: false,
  },
  {
    id: 'venue-22',
    slug: 'cap-city-comedy',
    cardArtUrl: '/assets/venue-art/comedy-v3austin.png',
    title: 'Cap City Comedy Club',
    venueName: 'Cap City Comedy Club',
    neighborhood: 'North Lamar',
    category: 'Comedy',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Stand-Up', 'Touring Comics'],
    ctaLabel: 'See Comedy picks',
    href: '/tonight?category=comedy',
    websiteUrl: 'https://capcitycomedy.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-23',
    slug: 'red-room-cap-city',
    cardArtUrl: '/assets/venue-art/comedy-v1warm.png',
    title: 'The Red Room at Cap City',
    venueName: 'The Red Room at Cap City',
    neighborhood: 'North Lamar',
    category: 'Comedy',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Stand-Up', 'Intimate Room'],
    ctaLabel: 'See Comedy picks',
    href: '/tonight?category=comedy',
    websiteUrl: 'https://capcitycomedy.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-24',
    slug: 'east-austin-comedy',
    cardArtUrl: '/assets/venue-art/comedy-weird-v6.png',
    title: 'East Austin Comedy Club',
    venueName: 'East Austin Comedy Club',
    neighborhood: 'East Austin',
    category: 'Comedy',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Stand-Up', '82-Seat Room'],
    ctaLabel: 'See Comedy picks',
    href: '/tonight?category=comedy',
    websiteUrl: 'https://eastaustincomedy.com',
    hasDetailPage: false,
  },
  {
    id: 'venue-25',
    slug: 'creek-and-the-cave',
    cardArtUrl: '/assets/venue-art/comedy-v2sharp.png',
    title: 'The Creek and The Cave',
    venueName: 'The Creek and The Cave',
    neighborhood: 'Downtown',
    category: 'Comedy',
    statusBadge: 'Preview pick',
    availabilityLabel: 'Verified listing',
    availabilityTone: 'steady',
    tags: ['Stand-Up', '7 Nights/Week'],
    ctaLabel: 'See Comedy picks',
    href: '/tonight?category=comedy',
    websiteUrl: 'https://creekandcave.com',
    hasDetailPage: false,
  },
];

export const HOMEPAGE_SIGNAL_ITEMS: HomepageSignalItem[] = [
  {
    id: 'signal-1',
    district: 'East 6th St',
    heatLabel: 'Hot',
    trendLabel: 'Very High Energy',
    categoryHint: 'Tonight Peak',
    href: '/signal?district=east-6th-st',
    rank: 1,
    mapX: '52%',
    mapY: '32%',
    previewSignals: [
      'Headliner shows on the Red River corridor',
      'Multiple late-night anchors carrying crowds',
      'Bar crawl traffic moving east through dirty 6th',
    ],
    anchorVenues: ['Mohawk', 'Stubb\u2019s', 'Cheer Up Charlies'],
    vibeNote: 'Loud, packed, live-music driven \u2014 the loudest district on a Friday night.',
  },
  {
    id: 'signal-2',
    district: 'Rainey St',
    heatLabel: 'Warm',
    trendLabel: 'High Energy',
    categoryHint: 'Open Late',
    href: '/signal?district=rainey-st',
    rank: 2,
    mapX: '48%',
    mapY: '82%',
    previewSignals: [
      'Bungalow bars consistently filling up after 9 PM',
      'Craft cocktail rooms holding steady late',
      'Heavy foot traffic between Rainey and Driskill blocks',
    ],
    anchorVenues: ['Bungalow', 'Banger\u2019s', 'Half Step'],
    vibeNote: 'Bungalow-bar density and craft cocktails \u2014 sociable but never sleepy.',
  },
  {
    id: 'signal-3',
    district: 'South Congress',
    heatLabel: 'Steady',
    trendLabel: 'Steady',
    categoryHint: 'Locals Night',
    href: '/signal?district=south-congress',
    rank: 3,
    mapX: '22%',
    mapY: '22%',
    previewSignals: [
      'Locals-night rhythm \u2014 reliable, not surging',
      'Dinner-to-drinks crossover from SoCo restaurants',
      'Lower wait times reported across anchor rooms',
    ],
    anchorVenues: ['Continental Club', 'C-Boy\u2019s', 'Hotel San Jos\u00e9'],
    vibeNote: 'Strolling pace, classic Austin character, lighter crowd than Rainey or East 6th.',
  },
  {
    id: 'signal-4',
    district: 'Downtown',
    heatLabel: 'Warm',
    trendLabel: 'Steady Flow',
    categoryHint: 'Skyline',
    href: '/signal?district=downtown',
    rank: 4,
    mapX: '36%',
    mapY: '56%',
    previewSignals: [
      'Rooftop bars trending busy after sunset',
      'Convention-adjacent foot traffic still elevated',
      'Mixed nightlife and dining crowd, no single peak',
    ],
    anchorVenues: ['Higher Ground', 'The Roosevelt Room', 'Garage'],
    vibeNote: 'Skyline rooftops and craft cocktail bars \u2014 polished, after-work to date-night.',
  },
  {
    id: 'signal-5',
    district: 'East Austin',
    heatLabel: 'Hot',
    trendLabel: 'Rising',
    categoryHint: 'Late Bars',
    href: '/signal?district=east-austin',
    rank: 5,
    mapX: '68%',
    mapY: '56%',
    previewSignals: [
      'Late-bar momentum building past midnight',
      'Patio scenes anchoring the early evening',
      'Pop-up and DJ programming clustered around East 11th',
    ],
    anchorVenues: ['Hotel Vegas', 'Whisler\u2019s', 'White Horse'],
    vibeNote: 'Patios, DJ rooms, late-bar momentum \u2014 the district rising fastest after midnight.',
  },
];

export const HOMEPAGE_CALENDAR_ITEMS: HomepageCalendarItem[] = [
  {
    id: 'calendar-1',
    dayLabel: 'Tonight',
    dateLabel: 'Preview · illustrative',
    timeLabel: '8:30 PM',
    title: 'The Format + Night Moves',
    venue: 'Mohawk Austin',
    neighborhood: 'Red River',
    category: 'Live Music',
    status: 'Preview pick',
    href: '/events',
  },
  {
    id: 'calendar-2',
    dayLabel: 'Tonight',
    dateLabel: 'Preview · illustrative',
    timeLabel: '10:00 PM',
    title: 'Late Show Stand-Up',
    venue: 'Cap City Comedy',
    neighborhood: 'North Lamar',
    category: 'Comedy',
    status: 'Preview pick',
    href: '/events',
  },
  {
    id: 'calendar-3',
    dayLabel: 'Tomorrow',
    dateLabel: 'Preview · illustrative',
    timeLabel: '11:00 AM',
    title: 'Rooftop Brunch Session',
    venue: 'Higher Ground',
    neighborhood: 'East Austin',
    category: 'Brunch',
    status: 'Preview pick',
    href: '/events',
  },
  {
    id: 'calendar-4',
    dayLabel: 'Tomorrow',
    dateLabel: 'Preview · illustrative',
    timeLabel: '8:00 PM',
    title: 'ACL Live Weekend Spotlight',
    venue: 'ACL Live',
    neighborhood: 'Downtown',
    category: 'Live Music',
    status: 'Featured',
    href: '/events',
  },
  {
    id: 'calendar-5',
    dayLabel: 'Sunday',
    dateLabel: 'Preview · illustrative',
    timeLabel: '1:00 PM',
    title: 'South Congress Patio Crawl',
    venue: 'South Congress Strip',
    neighborhood: 'South Congress',
    category: 'Cocktails',
    status: 'Walk-up friendly',
    href: '/events',
  },
  {
    id: 'calendar-6',
    dayLabel: 'Sunday',
    dateLabel: 'Preview · illustrative',
    timeLabel: '6:30 PM',
    title: 'Sunset Comedy + Cocktails',
    venue: 'East Austin Social',
    neighborhood: 'East Austin',
    category: 'Comedy',
    status: 'Locals pick',
    href: '/events',
  },
  {
    id: 'calendar-7',
    dayLabel: 'Next Week',
    dateLabel: 'Preview · illustrative',
    timeLabel: '7:30 PM',
    title: 'Antone\'s Blues Night',
    venue: 'Antone\'s',
    neighborhood: 'Downtown',
    category: 'Live Music',
    status: 'Preview pick',
    href: '/events',
  },
  {
    id: 'calendar-8',
    dayLabel: 'Next Week',
    dateLabel: 'Preview · illustrative',
    timeLabel: '9:00 PM',
    title: 'Rainey Late-Night Roundup',
    venue: 'Rainey Street District',
    neighborhood: 'Rainey Street',
    category: 'Dancing',
    status: 'Open late',
    href: '/events',
  },
];

export const HOMEPAGE_LOWER_MODULES: HomepageLowerModule[] = [
  {
    id: 'que-pasa',
    title: '¡Vive Austin!',
    caption: 'Preview of the future local feed and district heat — not source-fed yet.',
    icon: '\u2728',
    accent: 'pink',
    href: '/guides#people-places',
    eyebrow: 'Preview',
    honestyLabel: 'Preview',
  },
  {
    id: 'community',
    title: 'Community',
    caption: 'House rules and how the future local feed will work.',
    icon: '\u25c6',
    accent: 'violet',
    href: '/community-guidelines',
    eyebrow: 'Trust',
    honestyLabel: 'Guidelines available',
  },
  {
    id: 'pupper-weekly',
    title: 'Pupper Guide Preview',
    caption: 'Pet-friendly patios and dog-night guides — preview only.',
    icon: '\ud83d\udc3e',
    accent: 'amber',
    href: '/guides',
    eyebrow: 'Pets',
    honestyLabel: 'Guide preview',
  },
  {
    id: 'the-weather',
    title: 'Weather Layer Soon',
    caption: 'Weather layer coming soon — preview the placement here.',
    icon: '\u2604',
    accent: 'cyan',
    href: '/guides',
    eyebrow: 'Coming soon',
    honestyLabel: 'Coming soon',
  },
  {
    id: 'calendar',
    title: 'Events Preview',
    caption: 'Quick scan of the next few nights — preview slate, not source-fed.',
    icon: '\u2756',
    accent: 'lime',
    href: '/events',
    eyebrow: 'Plan ahead',
    honestyLabel: 'Events preview',
  },
];

export const HOMEPAGE_IMAGE_RAIL: HomepageImageRailItem[] = [
  {
    id: 'rail-1',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&q=80',
    caption: 'Crowd energy that feels like Austin, not a generic nightlife app.',
    neighborhood: 'Red River',
    category: 'Live Music',
    href: '/tonight?district=east-6th-st',
    rightsStatus: 'curated',
    attribution: 'Licensed stock placeholder (Unsplash) — not venue-permissioned media',
  },
  {
    id: 'rail-2',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200&q=80',
    caption: 'Food, drinks, and people/place texture belong in the frame.',
    neighborhood: 'East Austin',
    category: 'Late Eats',
    href: '/events',
    rightsStatus: 'curated',
    attribution: 'Licensed stock placeholder (Unsplash) — not venue-permissioned media',
  },
  {
    id: 'rail-3',
    image: 'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?w=1200&q=80',
    caption: 'Editorial nightlife mood beats a sterile event grid every time.',
    neighborhood: 'Rainey Street',
    category: 'Cocktails',
    href: '/tonight?district=rainey-st',
    rightsStatus: 'curated',
    attribution: 'Licensed stock placeholder (Unsplash) — not venue-permissioned media',
  },
];
